[pytest]
log_cli = true
log_cli_level = INFO
pythonpath = test
# PyTest should not recurse into the project directories,
# they may contain other unit tests.
testpaths =
    test/unit
    test/foss
norecursedirs =
    __pycache__
    .pytest_cache
    bazel-*
    .ci
