# Copyright 2023 Ericsson AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# cc_binary for simple C++ tests
load(
    "@rules_cc//cc:defs.bzl",
    "cc_binary",
    "cc_library",
)
load(
    "//src:codechecker.bzl",
    "codechecker_test",
)

# We are not interested in finding bugs, we are only interested in whether the
# analysis re-runs after the files have been modified. As such, these files emit no
# warnings.

cc_library(
    name = "linking",
    hdrs = ["linking.h"],
)

cc_library(
    name = "secondary",
    srcs = ["secondary.cc"],
    deps = ["linking"],
)

cc_binary(
    name = "primary",
    srcs = ["primary.cc"],
    deps = [
        "linking",
        "secondary",
    ],
)

codechecker_test(
    name = "codechecker_caching",
    targets = [
        "primary",
    ],
)

codechecker_test(
    name = "per_file_caching",
    per_file = True,
    targets = [
        "primary",
    ],
)

codechecker_test(
    name = "per_file_caching_ctu",
    analyze = ["--ctu"],
    per_file = True,
    targets = [
        "primary",
    ],
)
